### ISSUE TITLE
Add required hacktoberfest topic to this repo

### ISSUE THREAD

**Issue by MoyinShabi** [AhmadTakkoush/Hacktoberfest-2020-Flutter-Beginner#3]
To maintainer(s): I want to encourage you to please add the required `hacktoberfest` topic/label to this repository. This is encouraged due to the new rules set by the Hacktoberfest organizers as at October 3, 2020 (in all time zones) and this will enable new pull requests to this repo get counted for the Hacktoberfest 2020 challenge.

TL;DR- @AhmadTakkoush please check out this link explaining the updated rules here- [https://hacktoberfest.digitalocean.com/hacktoberfest-update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

I thought to create this issue before I contribute to this repo because I really want to.
I anticipate the update, thank you!

**Comment by AhmadTakkoush** [comment]
Thanks for the heads-up @MoyinShabi, the repo will be updated.

**Comment by MoyinShabi** [comment]
awesome, thank you!😊 @AhmadTakkoush
